#!/usr/bin/env python3
"""Create or verify the exact checksummed content identity of the runtime skill."""

from __future__ import annotations

_CACHE_PREFLIGHT_PATH = (
    __file__.replace("\\", "/").rsplit("/", 1)[0] + "/cache_preflight.py"
)
with open(_CACHE_PREFLIGHT_PATH, "rb") as _cache_preflight_stream:
    _CACHE_PREFLIGHT_SOURCE = _cache_preflight_stream.read()
exec(
    compile(_CACHE_PREFLIGHT_SOURCE, _CACHE_PREFLIGHT_PATH, "exec"),
    {
        "__file__": _CACHE_PREFLIGHT_PATH,
        "__name__": "_design_dna_cache_preflight",
    },
)
del _CACHE_PREFLIGHT_PATH, _CACHE_PREFLIGHT_SOURCE, _cache_preflight_stream

import argparse
import hashlib
import json
import os
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path

BOOTSTRAP_FAILURES: list[str] = []
try:
    import yaml
except ImportError as exc:  # pragma: no cover - exercised without dev dependencies
    yaml = None  # type: ignore[assignment]
    BOOTSTRAP_FAILURES.append(f"PyYAML: {exc}")

try:
    from jsonschema import Draft202012Validator, FormatChecker
except ImportError as exc:  # pragma: no cover - exercised without dev dependencies
    Draft202012Validator = None  # type: ignore[assignment]
    FormatChecker = None  # type: ignore[assignment]
    BOOTSTRAP_FAILURES.append(f"jsonschema: {exc}")

from common import (
    LOCAL_TOOL_DIRECTORY_NAMES,
    ToolFailure,
    absolute,
    assert_no_reparse_path,
    content_manifest,
    emit,
    entry_record,
    entry_exists,
    eval_content_manifest,
    is_within,
    load_json,
    reject_compiled_python_residue,
    strict_format_checker,
    walk_entries,
)


if yaml is not None:
    class NoDuplicateLoader(yaml.SafeLoader):
        pass


    def no_duplicate_mapping(loader, node, deep=False):
        result = {}
        for key_node, value_node in node.value:
            key = loader.construct_object(key_node, deep=deep)
            if key in result:
                raise yaml.constructor.ConstructorError(
                    "mapping",
                    node.start_mark,
                    f"duplicate key: {key}",
                    key_node.start_mark,
                )
            result[key] = loader.construct_object(value_node, deep=deep)
        return result


    NoDuplicateLoader.add_constructor(
        yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
        no_duplicate_mapping,
    )
else:
    NoDuplicateLoader = object  # type: ignore[assignment,misc]


UNSAFE_PORTABLE_PATH = re.compile(
    r"(?:^[/\\]|^[A-Za-z]:|\\|//|(?:^|/)\.{1,2}(?:/|$)|[\x00-\x1f\x7f])"
)

IDENTITY_GROUPS: dict[str, tuple[str, ...]] = {
    "maintainer_tooling": (
        "maintainer/scripts",
        "maintainer/requirements-dev.txt",
        "maintainer/requirements-dev.lock",
        "maintainer/package.json",
        "maintainer/package-lock.json",
    ),
    "schemas": ("maintainer/schemas",),
    "tests": ("maintainer/tests",),
    "eval_contract": (
        "maintainer/evals/README.md",
        "maintainer/evals/review-rubric.md",
        "maintainer/evals/schema.json",
        "maintainer/evals/fixtures",
    ),
    "evidence": ("maintainer/evidence",),
    "eval_proof": (
        "maintainer/evals/results",
        "maintainer/evals/reviews",
        "maintainer/evals/artifacts",
        "maintainer/evals/archive",
    ),
    "compatibility_verification": (
        "maintainer/compatibility",
        "maintainer/attestations",
    ),
    "distribution_docs": (
        ".gitattributes",
        ".gitignore",
        ".github",
        "README.md",
        "CHANGELOG.md",
        "CONTRIBUTING.md",
        "DATA_HANDLING.md",
        "LICENSE",
        "SECURITY.md",
        "SUPPORT.md",
        "THIRD_PARTY_NOTICES.md",
        "docs",
    ),
}
IDENTITY_COMPONENTS = {
    "distribution_tree",
    "runtime",
    "codex_plugin_manifest",
    "claude_plugin_manifest",
    "sbom",
    "compatibility_matrix",
    "trusted_adapters",
    *IDENTITY_GROUPS,
}
EXECUTABLE_MAINTAINER_TREES = (
    "maintainer/scripts",
    "maintainer/tests",
)


def reject_release_compiled_python_residue(
    plugin_root: Path,
    skill_root: Path,
) -> None:
    """Reject generated bytecode omitted from release identity hashes."""
    reject_compiled_python_residue(
        (
            skill_root,
            *(
                plugin_root / relative
                for relative in EXECUTABLE_MAINTAINER_TREES
            ),
        ),
        code="release-compiled-python-residue",
        message=(
            "Compiled Python residue is excluded from release identity and "
            "forbidden in runtime and executable maintainer trees."
        ),
    )


def reject_duplicate_json(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def stable_bytes(path: Path, *, stop: Path) -> bytes:
    """Read an identity input twice and fail if it changes during the read."""
    assert_no_reparse_path(path, stop=stop)
    try:
        first = path.read_bytes()
        second = path.read_bytes()
    except OSError as exc:
        raise ToolFailure("release-identity-input-unreadable", str(exc), path) from exc
    assert_no_reparse_path(path, stop=stop)
    if first != second:
        raise ToolFailure(
            "unstable-release-identity-input",
            "Identity input changed while it was being read.",
            path,
        )
    return first


def identity_group_sha256(
    plugin_root: Path,
    relative_paths: tuple[str, ...],
    *,
    include_generated: bool = False,
) -> str:
    """Hash a named set of files/directories, including explicit absence."""
    digest = hashlib.sha256()
    for relative in sorted(relative_paths):
        if UNSAFE_PORTABLE_PATH.search(relative):
            raise ToolFailure(
                "unsafe-release-identity-path",
                "Release identity inputs must use safe plugin-relative paths.",
                plugin_root / relative,
            )
        path = plugin_root / relative
        assert_no_reparse_path(path, stop=plugin_root)
        if path.is_file():
            kind = "file"
            item_digest = hashlib.sha256(
                stable_bytes(path, stop=plugin_root)
            ).hexdigest()
        elif path.is_dir():
            kind = "directory"
            manifest_function = (
                eval_content_manifest if include_generated else content_manifest
            )
            _records, item_digest = manifest_function(path)
        elif entry_exists(path):
            raise ToolFailure(
                "unsupported-release-identity-input",
                "Identity input must be a regular file, directory, or absent.",
                path,
            )
        else:
            kind = "absent"
            item_digest = ""
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(kind.encode("ascii"))
        digest.update(b"\0")
        digest.update(item_digest.encode("ascii"))
        digest.update(b"\0")
    return digest.hexdigest()


def identity_group_hashes(plugin_root: Path) -> dict[str, str]:
    return {
        name: identity_group_sha256(
            plugin_root,
            paths,
            include_generated=name == "eval_proof",
        )
        for name, paths in sorted(IDENTITY_GROUPS.items())
    }


def distribution_manifest(
    plugin_root: Path,
) -> tuple[list[dict[str, object]], str]:
    """Bind every distributable worktree entry except the circular manifest."""
    excluded = {"maintainer/release-manifest.json"}

    def collect() -> list[dict[str, object]]:
        raw_records = [
            entry_record(path, plugin_root)
            for path in walk_entries(
                plugin_root,
                ignored_directory_names=LOCAL_TOOL_DIRECTORY_NAMES,
            )
            if path.relative_to(plugin_root).as_posix() not in excluded
        ]
        # Git cannot preserve an empty directory. Binding one into the
        # distributable identity makes a clean clone differ from the source
        # worktree even though every tracked byte is identical. Keep files and
        # only the directory records needed to parent those files.
        required_directories: set[str] = set()
        for record in raw_records:
            if record.get("type") != "file":
                continue
            parts = str(record["path"]).split("/")
            for depth in range(1, len(parts)):
                required_directories.add("/".join(parts[:depth]))
        records = [
            record
            for record in raw_records
            if (
                record.get("type") == "file"
                or str(record.get("path")) in required_directories
            )
        ]
        records.sort(key=lambda item: str(item["path"]))
        return records

    records = collect()
    if records != collect():
        raise ToolFailure(
            "unstable-distribution-tree",
            "Distributable package content changed while it was hashed.",
            plugin_root,
        )
    digest = manifest_content_sha256(records)
    if digest is None:
        raise ToolFailure(
            "distribution-tree-invalid",
            "Distributable package records could not be hashed.",
            plugin_root,
        )
    return records, digest


def release_identity_sha256(components: dict[str, str]) -> str:
    digest = hashlib.sha256()
    for name, value in sorted(components.items()):
        digest.update(name.encode("ascii"))
        digest.update(b"\0")
        digest.update(value.encode("ascii"))
        digest.update(b"\0")
    return digest.hexdigest()


def strict_json_bytes(raw: bytes, path: Path) -> object:
    try:
        return json.loads(
            raw.decode("utf-8"),
            object_pairs_hook=reject_duplicate_json,
        )
    except (UnicodeError, json.JSONDecodeError, ValueError) as exc:
        raise ToolFailure("invalid-json", str(exc), path) from exc


def strict_yaml_bytes(raw: bytes, path: Path) -> object:
    if yaml is None:
        raise ToolFailure(
            "dependency-missing",
            "Install maintainer/requirements-dev.lock with --require-hashes (PyYAML is required).",
            path,
        )
    try:
        return yaml.load(raw.decode("utf-8"), Loader=NoDuplicateLoader)
    except (UnicodeError, yaml.YAMLError) as exc:
        raise ToolFailure("invalid-yaml", str(exc), path) from exc


def require_schema(instance: object, schema_path: Path, label: Path) -> None:
    if Draft202012Validator is None or FormatChecker is None:
        raise ToolFailure(
            "dependency-missing",
            "Install maintainer/requirements-dev.lock with --require-hashes (jsonschema is required).",
            label,
        )
    schema = load_json(schema_path)
    errors = sorted(
        Draft202012Validator(
            schema,
            format_checker=strict_format_checker(),
        ).iter_errors(instance),
        key=lambda item: tuple(str(part) for part in item.path),
    )
    if errors:
        message = "; ".join(
            f"{'/'.join(map(str, error.path)) or '<root>'}: {error.message}"
            for error in errors
        )
        raise ToolFailure("release-input-schema-invalid", message, label)


def manifest_content_sha256(files: object) -> str | None:
    """Recompute the content-manifest digest from validated-looking records."""
    if not isinstance(files, list):
        return None
    digest = hashlib.sha256()
    for record in files:
        if not isinstance(record, dict):
            return None
        path = record.get("path")
        kind = record.get("type")
        size = record.get("size")
        item_hash = record.get("sha256")
        if (
            not isinstance(path, str)
            or not isinstance(kind, str)
            or not isinstance(size, int)
            or (item_hash is not None and not isinstance(item_hash, str))
        ):
            return None
        try:
            digest.update(path.encode("utf-8"))
            digest.update(b"\0")
            digest.update(kind.encode("ascii", errors="strict"))
            digest.update(b"\0")
            digest.update(str(size).encode("ascii"))
            digest.update(b"\0")
            digest.update((item_hash or "").encode("ascii", errors="strict"))
            digest.update(b"\0")
        except UnicodeError:
            return None
    return digest.hexdigest()


def manifest_semantic_failures(
    payload: object,
    label: str | Path,
) -> list[dict[str, str]]:
    """Validate relationships JSON Schema cannot express."""
    failures: list[dict[str, str]] = []
    display = str(label)
    if not isinstance(payload, dict):
        return [{
            "code": "manifest-not-object",
            "path": display,
            "message": "Manifest must be an object.",
        }]
    files = payload.get("files")
    if not isinstance(files, list):
        return failures

    seen: dict[str, str] = {}
    kinds: dict[str, str] = {}
    paths: list[str] = []
    for index, record in enumerate(files):
        if not isinstance(record, dict) or not isinstance(record.get("path"), str):
            continue
        path = record["path"]
        paths.append(path)
        if (
            not path
            or path != path.strip()
            or path.endswith("/")
            or UNSAFE_PORTABLE_PATH.search(path)
        ):
            failures.append({
                "code": "manifest-unsafe-path",
                "path": display,
                "message": f"files/{index}: {path!r}",
            })
            continue
        key = path.casefold()
        if key in seen:
            failures.append({
                "code": "manifest-duplicate-path",
                "path": display,
                "message": f"{path!r} conflicts with {seen[key]!r}.",
            })
        else:
            seen[key] = path
            if isinstance(record.get("type"), str):
                kinds[key] = record["type"]

    if paths != sorted(paths):
        failures.append({
            "code": "manifest-path-order",
            "path": display,
            "message": "Manifest paths must be in deterministic ordinal order.",
        })

    for path in paths:
        parts = path.split("/")
        for depth in range(1, len(parts)):
            parent = "/".join(parts[:depth])
            parent_kind = kinds.get(parent.casefold())
            if parent_kind != "directory":
                failures.append({
                    "code": "manifest-parent-directory-missing",
                    "path": display,
                    "message": f"{path!r} requires directory entry {parent!r}.",
                })
                break

    recomputed_content = manifest_content_sha256(files)
    if (
        recomputed_content is not None
        and payload.get("content_sha256") != recomputed_content
    ):
        failures.append({
            "code": "manifest-content-hash-inconsistent",
            "path": display,
            "message": "content_sha256 does not match the ordered file records.",
        })
    distribution_files = payload.get("distribution_files")
    recomputed_distribution = manifest_content_sha256(distribution_files)
    if recomputed_distribution is None:
        failures.append({
            "code": "manifest-distribution-files-invalid",
            "path": display,
            "message": "distribution_files cannot be deterministically hashed.",
        })
    elif payload.get("distribution_sha256") != recomputed_distribution:
        failures.append({
            "code": "manifest-distribution-hash-inconsistent",
            "path": display,
            "message": (
                "distribution_sha256 does not match the complete distributable "
                "tree records."
            ),
        })
    components = payload.get("components")
    if isinstance(components, dict):
        component_names = set(components)
        if component_names != IDENTITY_COMPONENTS:
            failures.append({
                "code": "manifest-component-set-invalid",
                "path": display,
                "message": (
                    "components must contain exactly: "
                    + ", ".join(sorted(IDENTITY_COMPONENTS))
                ),
            })
        aliases = {
            "distribution_tree": payload.get("distribution_sha256"),
            "runtime": payload.get("content_sha256"),
            "codex_plugin_manifest": payload.get(
                "codex_plugin_manifest_sha256"
            ),
            "claude_plugin_manifest": payload.get(
                "claude_plugin_manifest_sha256"
            ),
            "sbom": payload.get("sbom_sha256"),
            "compatibility_matrix": payload.get("compatibility_matrix_sha256"),
            "trusted_adapters": payload.get("trusted_adapters_sha256"),
        }
        for name, alias in aliases.items():
            if components.get(name) != alias:
                failures.append({
                    "code": "manifest-component-alias-inconsistent",
                    "path": display,
                    "message": f"{name} does not match its top-level compatibility field.",
                })
        valid_components = {
            str(name): str(value)
            for name, value in components.items()
            if (
                isinstance(name, str)
                and isinstance(value, str)
                and re.fullmatch(r"[0-9a-f]{64}", value)
            )
        }
        expected_release = release_identity_sha256(valid_components)
        if payload.get("release_sha256") != expected_release:
            failures.append({
                "code": "manifest-release-hash-inconsistent",
                "path": display,
                "message": "release_sha256 does not match the named component hashes.",
            })
    return failures


def _load_sbom_helpers():
    """Resolve the sibling SBOM module from this file's own directory.

    A plain ``from build_sbom import ...`` here only works while the scripts
    directory happens to be on ``sys.path``. A caller that imports this module
    under a temporary path entry and then restores ``sys.path`` (which the
    maintainer tests correctly do) would otherwise fail at call time, long
    after the import that looked successful.
    """
    try:
        from build_sbom import generate_sbom, validate_sbom
    except ModuleNotFoundError:
        import importlib.util

        source = Path(__file__).resolve().parent / "build_sbom.py"
        spec = importlib.util.spec_from_file_location("build_sbom", source)
        if spec is None or spec.loader is None:  # pragma: no cover - defensive
            raise ToolFailure(
                "sbom-module-unavailable",
                "The SBOM module could not be loaded from the scripts directory.",
                source,
            )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        generate_sbom = module.generate_sbom
        validate_sbom = module.validate_sbom
    return generate_sbom, validate_sbom


def package_manifest(
    skill_root: Path,
    *,
    reject_compiled: bool = True,
) -> dict[str, object]:
    skill_root = absolute(skill_root)
    if (
        skill_root.name.casefold() != "design-dna"
        or skill_root.parent.name.casefold() != "skills"
    ):
        raise ToolFailure(
            "invalid-skill-root-layout",
            "Skill root must be the design-dna directory inside a plugin skills directory.",
            skill_root,
        )
    if not skill_root.is_dir():
        raise ToolFailure("skill-root-missing", "Runtime skill directory is missing.", skill_root)
    plugin_root = skill_root.parents[1]
    assert_no_reparse_path(skill_root, stop=plugin_root)
    assert_no_reparse_path(plugin_root)
    if reject_compiled:
        reject_release_compiled_python_residue(plugin_root, skill_root)
    schemas = plugin_root / "maintainer" / "schemas"
    files, digest = content_manifest(skill_root)
    release_path = skill_root / "release.json"
    release_raw = stable_bytes(release_path, stop=skill_root)
    release_record = next(
        (
            record
            for record in files
            if record.get("path") == "release.json" and record.get("type") == "file"
        ),
        None,
    )
    if (
        not isinstance(release_record, dict)
        or release_record.get("sha256") != hashlib.sha256(release_raw).hexdigest()
    ):
        raise ToolFailure(
            "unstable-runtime-release-input",
            "release.json did not match the stable runtime content snapshot.",
            release_path,
        )
    release = strict_json_bytes(release_raw, release_path)
    require_schema(
        release,
        schemas / "release.schema.json",
        release_path,
    )
    codex_plugin_path = plugin_root / ".codex-plugin" / "plugin.json"
    claude_plugin_path = plugin_root / ".claude-plugin" / "plugin.json"
    sbom_path = plugin_root / "maintainer" / "sbom.spdx.json"
    compatibility_path = plugin_root / "maintainer" / "compatibility" / "matrix.yml"
    trusted_adapters_path = (
        plugin_root
        / "maintainer"
        / "compatibility"
        / "trusted-host-adapters.yml"
    )
    codex_plugin_raw = stable_bytes(codex_plugin_path, stop=plugin_root)
    claude_plugin_raw = stable_bytes(claude_plugin_path, stop=plugin_root)
    sbom_raw = stable_bytes(sbom_path, stop=plugin_root)
    compatibility_raw = stable_bytes(compatibility_path, stop=plugin_root)
    trusted_adapters_raw = stable_bytes(trusted_adapters_path, stop=plugin_root)
    codex_plugin = strict_json_bytes(codex_plugin_raw, codex_plugin_path)
    claude_plugin = strict_json_bytes(claude_plugin_raw, claude_plugin_path)
    sbom = strict_json_bytes(sbom_raw, sbom_path)
    require_schema(
        codex_plugin,
        schemas / "plugin.schema.json",
        codex_plugin_path,
    )
    require_schema(
        claude_plugin,
        schemas / "claude-plugin.schema.json",
        claude_plugin_path,
    )
    require_schema(sbom, schemas / "sbom.schema.json", sbom_path)
    if (
        not isinstance(release, dict)
        or not isinstance(codex_plugin, dict)
        or not isinstance(claude_plugin, dict)
        or not isinstance(sbom, dict)
    ):
        raise ToolFailure(
            "invalid-release-input",
            "Release and both host plugin manifests must be objects.",
            plugin_root,
        )
    if codex_plugin.get("version") != release.get("version"):
        raise ToolFailure(
            "version-mismatch",
            "Codex plugin and runtime release versions must match.",
            codex_plugin_path,
        )
    if claude_plugin.get("version") != release.get("version"):
        raise ToolFailure(
            "version-mismatch",
            "Claude plugin and runtime release versions must match.",
            claude_plugin_path,
        )
    sbom_packages = sbom.get("packages")
    root_sbom_packages = [
        package
        for package in sbom_packages
        if isinstance(package, dict)
        and package.get("SPDXID") == "SPDXRef-Package-design-dna"
    ] if isinstance(sbom_packages, list) else []
    if (
        len(root_sbom_packages) != 1
        or root_sbom_packages[0].get("versionInfo") != release.get("version")
        or digest not in str(root_sbom_packages[0].get("sourceInfo", ""))
    ):
        raise ToolFailure(
            "sbom-runtime-identity-mismatch",
            "SBOM root package must bind the current version and runtime hash.",
            sbom_path,
        )
    creation_info = sbom.get("creationInfo")
    sbom_created = (
        creation_info.get("created")
        if isinstance(creation_info, dict)
        else None
    )
    if not isinstance(sbom_created, str):
        raise ToolFailure(
            "sbom-created-at-invalid",
            "SBOM creationInfo.created is missing.",
            sbom_path,
        )
    generate_sbom, validate_sbom = _load_sbom_helpers()

    validate_sbom(sbom, plugin_root)
    if generate_sbom(plugin_root, created_at=sbom_created) != sbom:
        raise ToolFailure(
            "sbom-drift",
            "SBOM differs from the current runtime, manifests, license, or dependency locks.",
            sbom_path,
        )
    compatibility = strict_yaml_bytes(compatibility_raw, compatibility_path)
    require_schema(
        compatibility,
        schemas / "compatibility.schema.json",
        compatibility_path,
    )
    if (
        not isinstance(compatibility, dict)
        or compatibility.get("package_version") != release.get("version")
    ):
        raise ToolFailure(
            "compatibility-version-mismatch",
            "Compatibility matrix and runtime release versions must match.",
            compatibility_path,
        )
    trusted_adapters = strict_yaml_bytes(
        trusted_adapters_raw,
        trusted_adapters_path,
    )
    require_schema(
        trusted_adapters,
        schemas / "trusted-host-adapters.schema.json",
        trusted_adapters_path,
    )
    codex_plugin_digest = hashlib.sha256(codex_plugin_raw).hexdigest()
    claude_plugin_digest = hashlib.sha256(claude_plugin_raw).hexdigest()
    sbom_digest = hashlib.sha256(sbom_raw).hexdigest()
    compatibility_digest = hashlib.sha256(compatibility_raw).hexdigest()
    trusted_adapters_digest = hashlib.sha256(
        trusted_adapters_raw
    ).hexdigest()
    distribution_files, distribution_digest = distribution_manifest(plugin_root)
    components = {
        "distribution_tree": distribution_digest,
        "runtime": digest,
        "codex_plugin_manifest": codex_plugin_digest,
        "claude_plugin_manifest": claude_plugin_digest,
        "sbom": sbom_digest,
        "compatibility_matrix": compatibility_digest,
        "trusted_adapters": trusted_adapters_digest,
        **identity_group_hashes(plugin_root),
    }
    release_digest = release_identity_sha256(components)
    manifest = {
        "schema_version": 6,
        "package": "design-dna",
        "version": release.get("version"),
        "distribution_sha256": distribution_digest,
        "content_sha256": digest,
        "codex_plugin_manifest_sha256": codex_plugin_digest,
        "claude_plugin_manifest_sha256": claude_plugin_digest,
        "sbom_sha256": sbom_digest,
        "compatibility_matrix_sha256": compatibility_digest,
        "trusted_adapters_sha256": trusted_adapters_digest,
        "components": components,
        "release_sha256": release_digest,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "files": files,
        "distribution_files": distribution_files,
    }
    verification_files, verification_digest = content_manifest(skill_root)
    if verification_files != files or verification_digest != digest:
        raise ToolFailure(
            "unstable-runtime-tree",
            "Runtime content changed while the release identity was being assembled.",
            skill_root,
        )
    if (
        stable_bytes(codex_plugin_path, stop=plugin_root) != codex_plugin_raw
        or stable_bytes(claude_plugin_path, stop=plugin_root)
        != claude_plugin_raw
        or stable_bytes(sbom_path, stop=plugin_root) != sbom_raw
        or stable_bytes(compatibility_path, stop=plugin_root) != compatibility_raw
        or stable_bytes(trusted_adapters_path, stop=plugin_root)
        != trusted_adapters_raw
        or identity_group_hashes(plugin_root)
        != {
            name: value
            for name, value in components.items()
            if name in IDENTITY_GROUPS
        }
    ):
        raise ToolFailure(
            "unstable-release-identity-input",
            (
                "Plugin manifests, maintainer, evidence, evaluation, or compatibility inputs changed "
                "while identity was assembled."
            ),
            plugin_root,
        )
    verification_distribution_files, verification_distribution_digest = (
        distribution_manifest(plugin_root)
    )
    if (
        verification_distribution_files != distribution_files
        or verification_distribution_digest != distribution_digest
    ):
        raise ToolFailure(
            "unstable-distribution-tree",
            "Distributable package content changed while identity was assembled.",
            plugin_root,
        )
    semantic = manifest_semantic_failures(manifest, skill_root)
    if semantic:
        raise ToolFailure(
            "generated-manifest-semantic-invalid",
            "; ".join(item["message"] for item in semantic),
            skill_root,
        )
    if reject_compiled:
        reject_release_compiled_python_residue(plugin_root, skill_root)
    return manifest


def comparable(payload: dict[str, object]) -> dict[str, object]:
    return {key: value for key, value in payload.items() if key != "generated_at"}


def historical_manifest_identity(
    payload: object,
    path: Path,
) -> tuple[str, str]:
    """Read the immutable comparison fields across manifest schema versions."""
    if not isinstance(payload, dict):
        raise ToolFailure(
            "previous-manifest-invalid",
            "Previous manifest must be a JSON object.",
            path,
        )
    schema_version = payload.get("schema_version")
    version = payload.get("version")
    identity = payload.get("release_sha256", payload.get("content_sha256"))
    if (
        payload.get("package") != "design-dna"
        or not isinstance(schema_version, int)
        or schema_version < 1
        or not isinstance(version, str)
        or not re.fullmatch(
            r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\."
            r"(?:0|[1-9][0-9]*)(?:[-+][0-9A-Za-z.-]+)?",
            version,
        )
        or not isinstance(identity, str)
        or not re.fullmatch(r"[0-9a-f]{64}", identity)
    ):
        raise ToolFailure(
            "previous-manifest-invalid",
            (
                "Previous manifest must contain a valid schema version, "
                "Design DNA package/version, and release or content identity."
            ),
            path,
        )
    return version, identity


def atomic_write(path: Path, payload: dict[str, object]) -> None:
    descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(payload, handle, indent=2, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    default_root = Path(__file__).resolve().parents[2] / "skills" / "design-dna"
    parser.add_argument("--skill-root", type=Path, default=default_root)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "release-manifest.json")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--previous", type=Path, help="Prior manifest; unchanged version with changed content fails.")
    args = parser.parse_args()
    if BOOTSTRAP_FAILURES:
        emit({
            "ok": False,
            "failures": [{
                "code": "dependency-missing",
                "message": (
                    "Install maintainer/requirements-dev.lock with --require-hashes. Missing: "
                    + "; ".join(BOOTSTRAP_FAILURES)
                ),
                "severity": "error",
                "path": str(Path(__file__).resolve()),
            }],
        })
        return 2
    try:
        root, output = absolute(args.skill_root), absolute(args.output)
        plugin_root = root.parents[1]
        if is_within(output, root):
            raise ToolFailure(
                "manifest-output-inside-runtime",
                "The release manifest must stay outside the installed runtime skill.",
                output,
            )
        if not output.parent.is_dir():
            raise ToolFailure(
                "manifest-output-parent-missing",
                "Create the exact output directory before writing a manifest.",
                output.parent,
            )
        assert_no_reparse_path(output, stop=output.parent)
        assert_no_reparse_path(output.parent)
        previous_path = absolute(args.previous) if args.previous else None
        if previous_path is not None and previous_path == output:
            raise ToolFailure(
                "previous-output-overlap",
                "--previous and --output must be different paths.",
                output,
            )
        generated = package_manifest(root)
        require_schema(
            generated,
            plugin_root / "maintainer" / "schemas" / "manifest.schema.json",
            output,
        )
        semantic_failures = manifest_semantic_failures(generated, output)
        if semantic_failures:
            emit({"ok": False, "manifest": str(output), "failures": semantic_failures})
            return 2
        failures: list[dict[str, str]] = []
        if previous_path is not None:
            assert_no_reparse_path(previous_path)
            prior = load_json(previous_path)
            prior_version, prior_identity = historical_manifest_identity(
                prior,
                previous_path,
            )
            if (
                prior_version == generated.get("version")
                and prior_identity != generated.get("release_sha256")
            ):
                failures.append({
                    "code": "version-not-bumped",
                    "message": "Release identity changed without a version change.",
                    "path": str(previous_path),
                })
        if args.check:
            existing = load_json(output)
            require_schema(
                existing,
                plugin_root / "maintainer" / "schemas" / "manifest.schema.json",
                output,
            )
            failures.extend(manifest_semantic_failures(existing, output))
            if not isinstance(existing, dict) or comparable(existing) != comparable(generated):
                failures.append({"code": "manifest-drift", "message": "Release manifest does not match runtime skill content.", "path": str(output)})
        elif not failures:
            try:
                atomic_write(output, generated)
            except OSError as exc:
                raise ToolFailure(
                    "manifest-write-failed",
                    str(exc),
                    output,
                ) from exc
        entries = generated["files"]
        emit({
            "ok": not failures, "manifest": str(output), "version": generated["version"],
            "content_sha256": generated["content_sha256"],
            "release_sha256": generated["release_sha256"],
            "entry_count": len(entries),
            "file_count": sum(item["type"] == "file" for item in entries),
            "directory_count": sum(item["type"] == "directory" for item in entries),
            "failures": failures,
        })
        return 1 if failures else 0
    except ToolFailure as exc:
        emit({"ok": False, "failures": [exc.issue.as_dict()]})
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
